config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"
  resources :users, only: [:index, :show]  do
    resources :posts, only: [:index, :show] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create, :destroy]
    end
  end

  resources :posts, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  def update_comment_counter
    post.increment!(:commentscounter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  after_create -> { update_like_counter_add }
  after_destroy -> { update_like_counter_remove }

  def update_like_counter_add
    post.increment!(:likescounter)
  end

  def update_like_counter_remove
    post.decrement!(:likescounter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :likes
  has_many :comments
  validates :title, presence: true
  validates :title, length: { maximum: 250 }
  validates :commentscounter, :likescounter, numericality: { greater_than_or_equal_to: 0 }

  def update_post_counter
    author.increment!(:postscounter)
  end

  def five_recent_comments
    comments.where(post: self).order(created_at: :desc).limit(5)
  end

  def liked?(user)
    likes.where(author: user).any?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, class_name: 'Post', foreign_key: 'author_id'
  has_many :comments, class_name: 'Comment', foreign_key: 'author_id'
  has_many :likes, class_name: 'Like', foreign_key: 'author_id'
  validates :name, presence: true
  validates :postscounter, numericality: { greater_than_or_equal_to: 0 }

  def three_recent_post
    posts.where(author: self).order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    permitted = params.require(:comment).permit(:text)
    @comment = Comment.new(text: permitted[:text], author_id: current_user.id, post_id: params[:post_id])
    if @comment.save
      redirect_to user_post_path(params[:user_id], params[:post_id])
    else
      render :new
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @post.likes.new(author: current_user)
    @post.save
    redirect_to user_post_path(@post.author, @post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @post.likes.where(author: current_user).destroy_all
    redirect_to user_post_path(@post.author, @post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
    @is_liked = @post.liked?(current_user)
    @comments = @post.comments
  end

  def new
    @post = Post.new
    @user = current_user
  end

  def create
    permitted = params.require(:post).permit(:title, :text)
    @post = Post.new(author: current_user, text: permitted[:text], title: permitted[:title], commentscounter: 0,
                     likescounter: 0)
    if @post.valid? && @post.save
      redirect_to user_post_path(current_user, @post)
    else
      render 'new'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h1 class="text-xl text-center font-bold">Add comment</h1>
<%= form_with model: [:user, :post, @comment], html: {class: "text-2xl flex flex-col"} do |form| %>
  <%= form.label :text, class: "font-bold mx-2 my-4 text-lg"  %>
  <%= form.text_area :text, rows: 10, class: "rounded-md border" %>
  <%= form.submit class: "border p-2 bg-sky-500 hover:bg-sky-600 my-2 font-bold rounded-md" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <main class="container mx-auto mt-2.5">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/index.html.erb
<div class="flex my-3 rounded-md border border-zinc-300">
  <img src="<%= @user.photo %>" class="w-1/5 rounded-l-md"/>
  <div class="w-4/5 px-2 pt-4 flex flex-col">
    <h2 class="text-2xl font-bold text-sky-600 hover:text-sky-700"><%= link_to @user.name, @user %></h2>
    <p class="text-sm text-right w-full font-bold">Number of Posts:
      <%= @user.posts.count %></p>
  </div>
</div>
<% @posts.each do |post| %>
  <div class="rounded-md border border-zinc-300 p-2 mb-4 bg-white/60 post_info">
    <h2
      class="
        font-semibold
        text-md
        text-sky-600
        hover:text-sky-700
        underline
        underline-offset-2
      "
    ><%= link_to post.title, [@user, post] %></h2>
    <p class="text-sm truncate my-2"><%= post.text %></p>
    <p class="text-right text-sm font-bold">Comments:
      <%= post.commentscounter %>
      Likes:
      <%= post.likescounter %></p>
    <hr>
    <h4 class="font-semibold mt-4">Most recent comments:</h4>
    <ul class="my-3 comments_container">
      <% post.comments.take(5).each do |comment| %>
        <li class="text-sm my-2">
          <span class="font-semibold"><%= comment.author.name %></span>
          says:
          <%= comment.text %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="flex flex-row justify-end">
  <a
    href="#"
    class="
      border
      border-zinc-300
      p-2
      bg-sky-600
      hover:bg-sky-700
      font-bold
      rounded-md
    "
  >Pagination</a>
</div>

app/views/posts/new.html.erb
<h1 class="text-xl text-center font-bold">Add new Post</h1>
<%= form_with model: @post, html: {class: "text-2xl flex flex-col"} do |form| %>
  <%= form.label :title, class: "font-bold mx-2 my-4 text-lg" %>
  <%= form.text_field :title, class: "rounded-md border" %>
  <%= form.label :text, class: "font-bold mx-2 my-4 text-lg"  %>
  <%= form.text_area :text, rows: 10, class: "rounded-md border"  %>
  <%= form.submit class: "border p-2 bg-sky-500 hover:bg-sky-600 my-2 font-bold rounded-md" %>
<% end %>

app/views/posts/show.html.erb
<div class="rounded-md border border-zinc-300 p-2 mb-4">
  <h2 class="font-semibold text-xl"><%= @post.title %> <small class="text-base">by <%= @post.author.name %></small></h2>
  <p class="text-right text-sm font-bold ">Comments:
    <%= @post.commentscounter || 0 %>
    Likes:
    <%= @post.likescounter || 0 %></p>
  <p class="my-4"><%= @post.text %></p>
  <hr>
  <h4 class="font-semibold mt-4">Comments:</h4>
  <p class="text-right my-2"><%= link_to 'Add Comment', new_user_post_comment_path(@post.author, @post), class: "border px-2 py-1 bg-sky-500 hover:bg-sky-600 font-bold rounded-md" %></p>
    <ul class="my-3 comments_container">
      <% @post.comments.each do |comment| %>
        <li class="text-sm my-2">
          <span class="font-semibold"><%= comment.author.name %></span> says: <%= comment.text %>
        </li>
      <% end %>
    </ul>
</div>
<% if !@is_liked %>
  <%= form_with url: user_post_likes_url(@post.author, @post) do |form| %>
    <%= button_tag class: "text-4xl fixed bottom-5 right-5 text-red-200" do  %>
      ❤️
    <% end %>
  <% end %>
<% else%>
  <%= form_with url: user_post_like_url(@post.author, @post), method: :delete do |form| %>
    <%= button_tag class: "text-4xl fixed bottom-5 right-5 text-red-500" do  %>
      ❤️
    <% end %>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav
  class="bg-white border-gray-200 px-2 sm:px-4 py-2.5 dark:bg-gray-900"
>
  <div class="container flex flex-wrap justify-between items-center mx-auto">
    <a href="<%= root_path%>" class="flex items-center">
      <img
        src="https://cdn.discordapp.com/attachments/946879758510202904/1012042401499594913/PngItem_4929898.png"
        class="mr-3 h-6 sm:h-9"
        alt="Flowbite Logo"
      >
      <span
        class="
          self-center
          text-xl
          font-semibold
          whitespace-nowrap
          dark:text-white
        "
      >Blog App</span>
    </a>
    <button
      data-collapse-toggle="navbar-default"
      type="button"
      class="
        inline-flex
        items-center
        p-2
        ml-3
        text-sm
        text-gray-500
        rounded-lg
        md:hidden
        hover:bg-gray-100
        focus:outline-none
        focus:ring-2
        focus:ring-gray-200
        dark:text-gray-400
        dark:hover:bg-gray-700
        dark:focus:ring-gray-600
      "
      aria-controls="navbar-default"
      aria-expanded="false"
    >
      <span class="sr-only">Open main menu</span>
      <svg
        class="w-6 h-6"
        aria-hidden="true"
        fill="currentColor"
        viewBox="0 0 20 20"
        xmlns="http://www.w3.org/2000/svg"
      ><path
          fill-rule="evenodd"
          d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
          clip-rule="evenodd"
        ></path></svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul
        class="
          flex
          flex-col
          p-4
          mt-4
          bg-gray-50
          rounded-lg
          border
          border-gray-100
          md:flex-row
          md:space-x-8
          md:mt-0
          md:text-sm
          md:font-medium
          md:border-0
          md:bg-white
          dark:bg-gray-800
          md:dark:bg-gray-900
          dark:border-gray-700
        "
      >
        <% if user_signed_in? %>
          <li>
            <%= link_to 'Profile', user_path(current_user.id), class:"block py-2 pr-4 pl-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white" %>
          </li>
          <li>
            <%= link_to 'Posts', user_posts_path(current_user.id), class: "block
              py-2
              pr-4
              pl-3
              text-gray-700
              rounded
              hover:bg-gray-100
              md:hover:bg-transparent
              md:border-0
              md:hover:text-blue-700
              md:p-0
              dark:text-gray-400
              md:dark:hover:text-white
              dark:hover:bg-gray-700
              dark:hover:text-white
              md:dark:hover:bg-transparent" %>

          </li>
          <li>
            <%= link_to 'New Post', new_post_path, class: "block
              py-2
              pr-4
              pl-3
              text-gray-700
              rounded
              hover:bg-gray-100
              md:hover:bg-transparent
              md:border-0
              md:hover:text-blue-700
              md:p-0
              dark:text-gray-400
              md:dark:hover:text-white
              dark:hover:bg-gray-700
              dark:hover:text-white
              md:dark:hover:bg-transparent" %>

          </li>
          <li>
            <%= button_to 'Sing out', destroy_user_session_path, method: :delete, class:" block
              py-2
              pr-4
              pl-3
              text-gray-700
              rounded
              hover:bg-gray-100
              md:hover:bg-transparent
              md:border-0
              md:hover:text-blue-700
              md:p-0
              dark:text-gray-400
              md:dark:hover:text-white
              dark:hover:bg-gray-700
              dark:hover:text-white
              md:dark:hover:bg-transparent" %>
          </li>
        <% else %>
          <li>
            <%= link_to 'Sing in', new_user_session_path, class:" block
              py-2
              pr-4
              pl-3
              text-gray-700
              rounded
              hover:bg-gray-100
              md:hover:bg-transparent
              md:border-0
              md:hover:text-blue-700
              md:p-0
              dark:text-gray-400
              md:dark:hover:text-white
              dark:hover:bg-gray-700
              dark:hover:text-white
              md:dark:hover:bg-transparent" %>
          </li>
          <li>
            <%= link_to 'Sing up', new_user_registration_path, class:" block
              py-2
              pr-4
              pl-3
              text-gray-700
              rounded
              hover:bg-gray-100
              md:hover:bg-transparent
              md:border-0
              md:hover:text-blue-700
              md:p-0
              dark:text-gray-400
              md:dark:hover:text-white
              dark:hover:bg-gray-700
              dark:hover:text-white
              md:dark:hover:bg-transparent" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/index.html.erb
<div class="flex flex-row justify-between">
  <h1 class="text-xl font-bold">List of users</h1>
</div>
<% @users.each do |user| %>
  <div class="flex my-4 border border-gray-700 h-20 rounded-md">
    <img src="<%= user.photo %>" class="object-scale-down rounded-l-md"/>
    <div class="px-2 pt-4 flex flex-col">
      <h2 class="text-lg font-bold text-sky-600 hover:text-sky-700"><%= link_to user.name, user %></h2>
      <p class="text-sm font-bold">Number of Posts:
        <%= user.posts.count %></p>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="flex my-3 rounded-md border">
  <img src="<%= @user.photo %>" class="w-1/5 rounded-l-md"/>
  <div class="w-4/5 px-2 pt-4 flex flex-col">
    <h2 class="text-2xl font-bold text-sky-600 hover:text-sky-700"><%= link_to @user.name, @user %></h2>
    <p class="text-sm text-right w-full font-bold">Number of Posts:
      <%= @user.posts.count %></p>
  </div>
</div>
<div class="rounded-md border border-zinc-300 p-2 bg-white">
  <h3 class="font-semibold">Bio</h3>
  <p class="text-sm"><%= @user.bio %></p>
</div>
<h2 class="font-bold mx-2 my-6 text-lg">
  Most recent posts by
  <%= @user.name %>:
</h2>
<% @user.three_recent_post.each do |post| %>
  <div class="rounded-md border border-zinc-300 p-2 mb-4 bg-white/60 post_info">
    <h2 class="font-semibold text-md underline underline-offset-2 text-sky-600 hover:text-sky-700"><%= link_to post.title, [@user, post] %></h2>
    <p class="text-sm truncate my-2"><%= post.text %></p>
    <p class="text-right text-sm font-bold">Comments:
      <%= post.commentscounter || 0 %>
      Likes:
      <%= post.likescounter || 0 %></p>
  </div>
<% end %>
<div class="flex flex-row justify-end">
  <%= link_to 'See all posts', user_posts_path(@user), class: "border bg-sky-500 hover:bg-sky-600 p-2 font-bold rounded-md" %>
</div>